- remote_user: ubuntu
  hosts: tag_Name_telemetry_regression_detector  # Assumes medusa is already deployed

  vars:
    - project_directory: "{{ansible_env.HOME}}/cerberus"

  tasks:
    - include: deps.yml

    - name: Install cerberus
      sudo: yes
      git: repo=git://github.com/mozilla/cerberus.git dest={{project_directory}} update=yes accept_hostkey=yes

    - name: Setup cron job
      sudo: yes
      cron: name=cerberus hour=5 job="{{project_directory}}/run.sh > /var/log/cerberus.log" cron_file=cerberus user=root

    - name: Restart cron
      sudo: yes
      service: name=cron state=restarted
